steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/campuslogics/blog:latest',
        '--build-arg', 'NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL',
        '--build-arg', 'NEXT_PUBLIC_GRAPHQL_API_URL=$_NEXT_PUBLIC_GRAPHQL_API_URL',
        '--build-arg', 'NODE_ENV=production',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/campuslogics/blog:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'nextjs-app',
        '--image', 'gcr.io/$PROJECT_ID/campuslogics/blog:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/campuslogics/blog:latest'

substitutions:
  _NEXT_PUBLIC_BASE_URL: "https://www.campuslogics.org/"
  _NEXT_PUBLIC_GRAPHQL_API_URL: "https://www.campuslogics.org/api/graphql"