FROM node:22-alpine AS builder
RUN apk add --no-cache openssl
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

ARG IMAGEKIT_PUBLIC_KEY
ARG IMAGEKIT_URL_ENDPOINT
ARG IMAGEKIT_PRIVATE_KEY
ARG ADMIN_DATA
ARG AUTH_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_GRAPHQL_API_URL
ARG NODE_ENV
ARG DATABASE_URL
ARG NEXTAUTH_SECRET
ARG YOUTUBE_API_KEY
ARG YOUTUBE_CHANNEL_ID


ENV IMAGEKIT_PUBLIC_KEY=$IMAGEKIT_PUBLIC_KEY
ENV IMAGEKIT_URL_ENDPOINT=$IMAGEKIT_URL_ENDPOINT
ENV IMAGEKIT_URL_ENDPOINT=$IMAGEKIT_PRIVATE_KEY
ENV IMAGEKIT_PRIVATE_KEY=$ADMIN_DATA
ENV IMAGEKIT_PRIVATE_KEY=$AUTH_URL
ENV IMAGEKIT_PRIVATE_KEY=$NEXT_PUBLIC_BASE_URL
ENV IMAGEKIT_PRIVATE_KEY=$NEXT_PUBLIC_GRAPHQL_API_URL
ENV IMAGEKIT_PRIVATE_KEY=$NODE_ENV
ENV IMAGEKIT_PRIVATE_KEY=$DATABASE_URL
ENV IMAGEKIT_PRIVATE_KEY=$NEXTAUTH_SECRET
ENV IMAGEKIT_PRIVATE_KEY=$YOUTUBE_API_KEY
ENV IMAGEKIT_PRIVATE_KEY=$YOUTUBE_CHANNEL_ID


COPY . .
RUN npm run build

# ---- production image ----
FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
