FROM node:22-alpine AS builder
RUN apk add --no-cache openssl
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

ARG IMAGEKIT_PUBLIC_KEY
ARG IMAGEKIT_URL_ENDPOINT
ARG IMAGEKIT_PRIVATE_KEY
ARG ADMIN_DATA
ARG AUTH_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_GRAPHQL_API_URL
ARG NODE_ENV
ARG DATABASE_URL
ARG NEXTAUTH_SECRET
ARG YOUTUBE_API_KEY
ARG YOUTUBE_CHANNEL_ID


ENV IMAGEKIT_PUBLIC_KEY=$IMAGEKIT_PUBLIC_KEY
ENV IMAGEKIT_URL_ENDPOINT=$IMAGEKIT_URL_ENDPOINT
ENV IMAGEKIT_PRIVATE_KEY=$IMAGEKIT_PRIVATE_KEY
ENV ADMIN_DATA=$ADMIN_DATA
ENV AUTH_URL=$AUTH_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_GRAPHQL_API_URL=$NEXT_PUBLIC_GRAPHQL_API_URL
ENV NODE_ENV=$NODE_ENV
ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV YOUTUBE_API_KEY=$YOUTUBE_API_KEY
ENV YOUTUBE_CHANNEL_ID=$YOUTUBE_CHANNEL_ID


COPY . .
RUN npm run build

# ---- production image ----
FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
